# Generated by Django 4.2 on 2023-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_accountmodel_uploadmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='Book_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='Isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='cover_page',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
